'use client';

import React from 'react';
import { motion } from 'framer-motion';

export default function OptimizationShowcase() {
    return (
        <div className="min-h-screen bg-neutral-900 text-white p-8 font-sans">
            <header className="mb-12 text-center">
                <h1 className="text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-purple-600">
                    Trinity Demo: Optimization Journey
                </h1>
                <p className="mt-4 text-neutral-400">From Prototype to Localized Product in 3 Iterations</p>
            </header>

            <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
                {/* V1 Stage */}
                <Section
                    title="V1: The Prototype"
                    desc="User: 'Generate a popular Match-3 game.'"
                    tags={['Boy Theme', 'Candy', 'Global Generic']}
                    color="border-blue-500"
                >
                    <AssetRow prefix="v1" assets={['home.jpg', 'gameplay.jpg', 'victory.jpg']} />
                </Section>

                {/* V2 Stage */}
                <Section
                    title="V2: The Pivot"
                    desc="User: 'Change to cute girl & fruit theme.'"
                    tags={['Girl Theme', 'Fruit', 'Mobile 9:16']}
                    color="border-green-500"
                >
                    <AssetRow prefix="v2" assets={['home.png', 'gameplay.png', 'victory.png']} />
                </Section>

                {/* V3 Stage */}
                <Section
                    title="V3: Localization"
                    desc="User: 'Make it Chinese style (Hanfu).'"
                    tags={['Hanfu Girl', 'Chinese Text', 'Cultural']}
                    color="border-red-500"
                >
                    <AssetRow prefix="v3" assets={['home.png', 'store.png', 'gameplay.png', 'shop.png', 'victory.png']} />
                </Section>
            </div>

            <footer className="mt-20 text-center border-t border-neutral-800 pt-8">
                <p className="text-sm text-neutral-500">Generated by Trinity AI Game Designer Co-Pilot</p>
            </footer>
        </div>
    );
}

function Section({ title, desc, tags, children, color }: { title: string, desc: string, tags: string[], children: React.ReactNode, color: string }) {
    return (
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className={`bg-neutral-800 rounded-xl p-6 border-t-4 ${color} shadow-2xl`}
        >
            <h2 className="text-2xl font-bold mb-2">{title}</h2>
            <p className="text-sm text-neutral-400 mb-4 italic">"{desc}"</p>
            <div className="flex flex-wrap gap-2 mb-6">
                {tags.map(tag => (
                    <span key={tag} className="px-2 py-1 bg-neutral-700 rounded text-xs text-neutral-300">{tag}</span>
                ))}
            </div>
            <div className="space-y-4">
                {children}
            </div>
        </motion.div>
    );
}

function AssetRow({ prefix, assets }: { prefix: string, assets: string[] }) {
    return (
        <div className="grid grid-cols-2 gap-2">
            {assets.map((asset, i) => (
                <div key={i} className="relative aspect-[9/16] bg-neutral-900 rounded-lg overflow-hidden border border-neutral-700 group hover:border-white transition-colors">
                    <img
                        src={`/assets/demo_opt/${prefix}_${asset}`}
                        alt={`${prefix} ${asset}`}
                        className="object-cover w-full h-full"
                    />
                    <div className="absolute bottom-0 left-0 right-0 bg-black/60 p-1 text-[10px] text-center text-white backdrop-blur-sm opacity-0 group-hover:opacity-100 transition-opacity">
                        {asset.split('.')[0]}
                    </div>
                </div>
            ))}
        </div>
    );
}
